---
platform: linux/arm64

pipeline:
  createimage:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ls -l ./
      - ls -l /var/run/
      - docker build -t miyoo_buildbot .
      - chmod -R o+rw ./

# Setup secrets
  install_secrets:
    image: miyoo_buildbot
    secrets: [tftp_ssh_key]
    commands:
      - mkdir ./secrets/ && echo "$SSH_KEY" > ./secrets/tftp_ssh_key && chmod 0600 ./secrets/tftp_ssh_key

# Boot strap
  bootstrap:
    image: miyoo_buildbot
    commands:
      - make bootstrap

# DL
  dl:
    image: miyoo_buildbot
    volumes:
      - /var/local/ci_cache/buildroot_dl:/var/local/ci_cache/buildroot_dl
    commands:
      - ln -s /var/local/ci_cache/buildroot_dl dl
      - make buildroot-dl

# do it!
  build:
    image: miyoo_buildbot
    volumes:
      - /var/local/ci_cache/buildroot_dl:/var/local/ci_cache/buildroot_dl
      - /var/local/ci_cache/ccache:/var/local/ci_cache/ccache
    commands:
      - ln -s /var/local/ci_cache/ccache ccache
      - make

## HERE IMAGES SHOULD BE UPLOADED

...
